
DROP TABLE IF EXISTS stores CASCADE;
CREATE TABLE stores (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  location VARCHAR(255) NOT NULL UNIQUE,
  longitude VARCHAR(255) NOT NULL UNIQUE,
  latitude VARCHAR(255) NOT NULL UNIQUE
);
