DROP TABLE IF EXISTS sub_categories CASCADE;
CREATE TABLE sub_categories (
  id SERIAL PRIMARY KEY NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL UNIQUE
);
