DROP TABLE IF EXISTS sub_categories CASCADE;
CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL UNIQUE,

);
