INSERT INTO products (sub_category_id, store_id, make, model, price_in_cents, description, image_url) VALUES
(1, 1, 'Gibson', 'J-45 Standard Vintage Sunburst', 389900, 'The J-45 is Gibsons best-selling acoustic of all time. Nicknamed The Workhorse and first introduced in 1942, this iconic acoustic has become the cornerstone of its round-shoulder, dreadnought line. World renowned for its full, balanced expression, warm bass and excellent projection, the J-45 has been refined to carry this legacy to new heights. This 2019 model delivers a sound with incredible dynamic range, warm mids, and a tight punchy bass.', 'https://cdn.long-mcquade.com/files/122144/lg_0849cf1739933778466c260a39932bde.webp?alt=J-45%20Standard%20Vintage%20Sunburst'),
(1, 1, 'Taylor Guitars', 'Grand Auditorium All-Koa Solid-Top Acoustic Guitar', 244900, 'Fans of Hawaiian koa will love the look, feel and sound of this all-koa Grand Auditorium. A shaded edgeburst elevates the vintage appeal of the solid koa top, which is paired with layered koa back and sides, while a gloss finish wraps the body in a rich sheen. The Grand Auditoriums musical versatility makes this a great all-purpose guitar for both strumming and fingerpicking, and the hardwood koa top will even out a lively attack to produce a focused, linear voice. Player-friendly modern features include a cutaway and Taylors ES2 acoustic electronics. Among the distinctive appointments are a single-ring faux pearl rosette in an interlocking fishbone pattern, black binding, Italian acrylic small diamond inlays, and chrome tuners. The guitar ships in a Taylor deluxe hardshell case.', 'https://cdn.long-mcquade.com/files/90855/lg_7752578b7901b1723e9c212e765b6f13.webp?alt=Grand%20Auditorium%20All-Koa%20Solid-Top%20Acoustic/Electric%20Guitar'),
(1, 1, 'Ibanez','AE295 Acoustic Guitar - Natural High Gloss', 90999, 'Born from a long lineage and musical heritage, the acoustic guitar is steeped in tradition. But music continues to evolve, and musicians demand inspiring new tools with which to carve out their own signature sound. In that spirit, we introduce Ibanez AE, our flagship series of acoustic-electric guitars, offer supreme tone and playability, and represent another great chapter in the acoustic guitar tradition.', 'https://cdn.long-mcquade.com/files/262376/lg_e7cafadc622c4a0d0f560350b4778ff5.webp?alt=AE295%20Acoustic/Electric%20Guitar%20-%20Natural%20High%20Gloss'),
(1, 1, 'Gretsch Guitars','G9500 Jim Dandy Flat Top Acoustic Guitar - 2 Color Sunburst', 25900, 'Crackerjack quality at a sober price! Faithfull to the Gretsch Rex parlor guitars of the 1930s, 40s and 50s, the all-new G9500 Jim Dandy Flat Top parlor-style model embodies everything that was great about everyones first guitar. Everything and then some, that is, because the G9500 is crafted with select guitar woods and is fully lined and braced for warm and pleasing tone, with a 24 inch scale for endless hours of playing comfort', 'https://cdn.long-mcquade.com/files/48249/lg_2704000503v1_hi.webp?alt=G9500%20Jim%20Dandy%20Flat%20Top%20Acoustic%20Guitar%20-%202-Color%20Sunburst'),
(2, 1, 'Fender','American Professional II Stratocaster, Rosewood Fingerboard - 3-Colour Sunburst', 234999, 'The American Professional II Stratocaster® draws from more than sixty years of innovation, inspiration and evolution to meet the demands of todays working player.

Fenders popular Deep C neck now sports smooth rolled fingerboard edges, a Super-Natural satin finish and a newly sculpted neck heel for a supremely comfortable feel and easy access to the upper register. New V-Mod II Stratocaster single-coil pickups are more articulate than ever while retaining bell-like chime and warmth. An upgraded 2-point tremolo with a cold-rolled steel block increases sustain, clarity and high-end sparkle.

The American Pro II Stratocaster delivers instant familiarity and sonic versatility youll feel and hear right away, with broad ranging improvements that add up to nothing less than a new standard for professional instruments.

Deluxe molded case included.', 'https://cdn.long-mcquade.com/files/209500/lg_1_1_0737197.webp?alt=American%20Professional%20II%20Stratocaster,%20Rosewood%20Fingerboard%20-%203-Colour%20Sunburst'),
(2, 1, 'Gibson','Les Paul Classic - Ebony', 339900, 'The Gibson Les Paul Classic combines the early 60s style Les Paul model with some functional and time-tested modications. As expected, the LP Classic is crafted with a mahogany back and maple top coupled with a slim taper mahogany neck and bound, rosewood fingerboard. Burstbucker 61R & 61T zebra, open-coil pickups provide classic Gibson tones from the era with a bit of extra punch thanks to the open coils. The control assembly features 4 push-pull pots which provide choices of coil tapping, phase switching and pure bypassing for functional and versatile sonic variety.', 'https://cdn.long-mcquade.com/files/136240/lg_6b2963b73c81e248bfd94d280068ec52.webp?alt=Les%20Paul%20Classic%20-%20Ebony'),
(2, 1, 'Ibanez','RG450DXB Electric Guitar - White', 62999, 'Jatoba Fretboard - Jatoba has a reddish brown color which produces a rich mid range with a crisp high end.
Quantum Pickups - The Quantum pickups provide accelerated bass response for exceptionally fast tracking of high-speed staccato riffing with crushing mid range and precise high-end articulation.
Wizard III Maple Neck - Ibanezs thin, flat and fast Wizard neck is strong and sturdy and offers unlimited playability and features a two-octave 24-fret fretboard for a wide tonal range.', 'https://cdn.long-mcquade.com/files/273716/lg_0d41cb73921d4b03500e9435cc966be6.webp?alt=RG450DXB%20Electric%20Guitar%20-%20White'),
(2, 1, 'Danelectro','59X12 12-String Electric Guitar - Vintage Cream', 96500, 'Danelectros best sounding 12 string ever. Chimey, sparkly, jangly. A treat to eyes and ears.', 'https://cdn.long-mcquade.com/files/152688/lg_a6f1e105656c286646019bf2e5da5ded.webp?alt=59X12%2012-String%20Electric%20Guitar%20-%20Vintage%20Cream'),
(3, 1, 'Fender','Player Series Mustang Bass PJ with Pau Ferro Fingerboard - Aged Natural', 116999, 'Since its original release in 1964, the Mustang Bass has been one of Fenders most enduring bass designs, finding its way into the hands of bassists ranging from The Rolling Stones to My Chemical Romance.
This updated version of the short-scale underground hero adds the power of Fenders venerable P Bass and J Bass pickups - a punchy split single-coil P Bass middle pickup and a growling Jazz Bass bridge pickup in an unbeatable pairing that combines the best of both sonic worlds. Not only is the 30" scale more comfortable for smaller hands, it reduces string tension, creating a looser playing feel that lends itself to nimble playing styles while adding a fat, blooming quality to the lower notes and sweetening the higher notes. Topped by a 9.5"-radius Pau Ferro fingerboard with 19 medium jumbo frets, the "C"-shaped maple neck is comfortable for all playing styles.
This bass smaller body easily fits those with smaller frames while maintaining Fenders classic stylistic appeal, and is also great for energetic stage performances thanks to its light weight. In a nod to its roots, this modernized instrument includes vintage-style Fender tuning machines and a vintage-style disc string tree, along with a four-bolt neck plate and standard four-saddle bridge- all finished in gleaming chrome.
A classic instrument, upgraded with features for the modern bassist, the short-scale Mustang Bass PJ is sure to please with its flexible sound, easy playing feel and slick style.', 'https://cdn.long-mcquade.com/files/165276/lg_1_1_726025.webp?alt=Player%20Series%20Mustang%20Bass%20PJ%20with%20Pau%20Ferro%20Fingerboard%20-%20Aged%20Natural'),
(3, 1, 'Ernie Ball Music Man','StingRay 5 Special HH 5-String Bass - Amethyst Sparkle', 389900, 'The first bass designed by Ernie Ball Music Man, the Stingray 5 was unveiled in 1987 and has been an industry standard for extended range basses ever since. With its powerful punchy sound, the added flexibility of additional pickups, and a comfortably contoured body, the StingRay 5 satisfies even the most demanding of players.

Powerful Neodymium Pickups
The new and improved StingRay electronics feature powerful neodymium magnets, bringing you more output and a wider range of sounds

New 18-Volt Preamp
A newly designed 18-volt 3-Band preamp for extra clean headroom lets you dial in everything from modern punch to classic, vintage tones.

Lightweight Performance
The overall reduction in weight is a much-welcomed feature of the new Stingray Special. Select body woods, improved contours, and lightweight hardware provide greater overall balance for extra comfort and a more enjoyable playing experience.', 'https://cdn.long-mcquade.com/files/250581/lg_90f9308d45c45190ee8614f89e991f59.webp?alt=StingRay%205%20Special%20HH%205-String%20Bass%20-%20Amethyst%20Sparkle'),
(3, 1, 'Gibson','Rex Brown Thunderbird - Ebony', 377900, 'Multi-instrumentalist Rex Brown is well-known for his work with legendary metal bands Pantera, Down, and Kill Devil Hill, and his hard-rocking solo album, Smoke on This. His New Gibson Rex Brown Signature Thunderbird bass features a mahogany neck and body, and gold hardware with a Hipshot bridge and tuners (including a DropD Xtender). A pair of powerful Rexbucker T-Bird pickups provide plenty of output and low-end punch. The master tone control is equipped with a push//pull switch that puts the pickups into passive mode when it is pulled out. Rexs signature is reproduced on the trussrod cover, and the back plate is embellished with a Rex Brown doodle. A modern series hardshell case is also included.', 'https://cdn.long-mcquade.com/files/288731/lg_c1b9b1748e911fb13bddfa0bfb308fc4.webp?alt=Rex%20Brown%20Thunderbird%20-%20Ebony'),
(3, 1, 'Hofner','Ignition Pro Violin Bass - Sunburst', 63999, 'The Ignition Pro Edition basses are based on the Hofner violin basses from the 1970s. In contrast to the Contemporary series, the Ignition basses have a hollow body. In addition to the classic control panel with Tea Cup knobs, they are equipped with a wooden bridge, a trapeze tailpiece and are fitted with Hofner flatwound strings for that unique 60s sound. Fully hollow this bass produces the distinctive Hofner deep and resonant bass tone so loved by musicians everywhere. Lightweight, it can be played easily for hours without breaking your back!', 'https://cdn.long-mcquade.com/files/292891/lg_b4fc1df671e50d34e2ea3619e78bb629.webp?alt=Ignition%20Pro%20Violin%20Bass%20-%20Sunburst'),
(4, 1, 'Roland','F701 Digital Piano with Stand and Bench - Charcoal Black', 224999, 'The streamlined piano for the modern home. If youre learning piano as a new hobby or just looking to start playing again, you want to pick an instrument that matches your style. While some traditional pianos can look out of place with modern furnishings, the F701 is made with the contemporary home in mind, offering a stylish, understated cabinet and compact size that fits easily in smaller spaces. Yet while the minimal aesthetic seamlessly blends with your decor and subtly enhances the look of any room, the F701s performance as a musical instrument is bold and commanding.
Youll play with greater expression, thanks to Rolands dynamic SuperNATURAL sound engine and PHA-4 Standard keyboard that responds to the slightest touch. And your home will be filled with beautiful piano sound, thanks to the powerful twin speaker system. For total concentration during practice, dive into the Headphones 3D Ambience effect for an immersive sound field that encourages you to lose yourself in the music. Youll practice more often and learn faster too, using integrated Bluetooth audio and MIDI to explore everything from YouTube video lessons to dedicated music apps.
Slide open the lid, select a sound to match your mood, and experience the F701: a thoroughly modern piano that looks - and feels - as good as it sounds.', 'https://cdn.long-mcquade.com/files/218811/lg_d3fa5d10696d959d309f3ebac7663d07.webp?alt=F701%20Digital%20Piano%20with%20Stand%20and%20Bench%20-%20Charcoal%20Black'),
(4, 1, 'Roland','GP-3-PE Digital Grand Piano - Polished Ebony', 599999, 'Low-profile grand piano with a space-saving footprint, elegant details, and premium Roland piano technologies.

The GP-3 is the most compact and affordable grand in the acclaimed GP series, bringing you premium piano performance in a unique low-profile design that makes a statement in any living space. Rolands modern features and benefits are infused throughout, from the organic piano sound engine and responsive hammer-action keyboard to onboard recording, Bluetooth audio/MIDI connectivity, and deep integration with the Roland Piano App. If youve always wanted a grand piano but thought you didnt have the space or budget to make it happen, the GP-3 turns your dream into reality.', 'https://cdn.long-mcquade.com/files/312271/lg_8626671d29c046b8906088c9e17561bd.webp?alt=GP-3-PE%20Digital%20Grand%20Piano%20-%20Polished%20Ebony'),
(4, 1, 'Yamaha','NP12 Piaggerro 61 Key Portable Keyboard - Black', 30999, 'Exquisite tone in a light, compact instrument - the Piaggero NP Series portable keyboards are an ideal combination of elegance and simplicity. Designed around the essential elements that let you concentrate on playing, NP Series keyboards focus on the inspiration and enjoyment of playing a piano, and feature the pure tone of one of the finest grand pianos that Yamaha has ever made.'
, 'https://cdn.long-mcquade.com/files/71386/lg_ee3b918194b88cabb400f1b1478e469b.webp?alt=NP12%20Piaggerro%2061%20Key%20Portable%20Keyboard%20-%20Black'),
(4, 1, 'Casio','CDP-S160 88-key Digital Piano - Red', 30999, 'Realistic, portable, and comfortable to play, the CDP-S160 redefines value in a digital piano. Its a perfect piano for students, hobbyists, or pianists who need grand piano sound and feel in a small space.
', 'https://cdn.long-mcquade.com/files/273956/lg_7281b630a2baa8fb63fa2fa81dbbdc2f.webp?alt=CDP-S160%2088-key%20Digital%20Piano%20-%20Red'),
(5, 1, 'Akai','MPK Mini MKIII 25-Note Keyboard/Drum Pad Controller', 12900, 'Your entry-point into a world of pro production starts here. Introducing the MPK mini mk3, the third iteration of the worlds legendary best-selling mini keyboard controller that redefined how a generation of creators makes music.', 'https://cdn.long-mcquade.com/files/188288/lg_70b33a2b3aea176fca66814191d84368.webp?alt=MPK%20Mini%20MKIII%2025-Note%20Keyboard/Drum%20Pad%20Controller'),
(5, 1, 'Novation','Launchkey Mini Mk3 25-Key MIDI Controller', 14900, 'Launchkey Mini is Novations most compact and portable 25-mini-key MIDI keyboard controller. It gives you everything you need to start creating in Ableton Live - and compact enough to fit in your bag. Make tracks anywhere with Launchkey Minis intuitive Ableton control, creative arpeggiator, Fixed Chord mode, MIDI out, and tons of sounds in the box.

Get Creative
Get new melodies, rhythms and sounds flying from your fingertips with Launchkey Minis easy yet powerful arpeggiator. Fixed Chord mode takes your ideas further, adding a customisable fixed chord shape that follows you up the keyboard. Add dynamic, expressive rhythms with 16 super-sensitive pads for drumming and clip launch.

Your Tracks, Your Way
Step back from the screen and feel the beats. Launchkey Minis deep and intuitive integration with Live lets you move where the music takes you. Transport, device and mixer controls mean fewer mouse clicks. Device macros and mixer controls mean more hands-on control of your music. Launchkey Mini puts the sounds from your head into your hands.

Included Sounds, Instruments and Effects
AAS Session Bundle, Softube Time & Tone, exclusive Spitfire Audio LABS - Expressive Strings instrument, Klevgrand DAW Casette and R0Verb, and access one of four virtual keyboards when you register your first piece of Novation or Focusrite hardware.', 'https://cdn.long-mcquade.com/files/155572/lg_d10f3c667f1d1a8947cbbedd585d6a21.webp?alt=Launchkey%20Mini%20Mk3%2025-Key%20MIDI%20Controller'),
(5, 1, 'Arturia','KeyStep Pro Sequencer/Controller', 61999, 'An all-in-one sequencing solution
Take full control of your modular rigs, outboard synths, and software studio all at the same time. If you prefer keys to pads, youre in for a treat. KeyStep Pro features a great-feeling 3 octave keyboard with velocity sensitivity and aftertouch. Letting you fully articulate your musical ideas, this expressive little sequencer truly puts the power at your fingertips.

Powerful Performance Controls
KeyStep Pro makes gigging easy and fun, with instant and intuitive access to inspiring performance features. Multi-mode arpeggiator, randomness, easy chord mode, and real-time recording for creating on the fly. The crisp OLED displays and LED-illuminated controls will help you see it all in the dark, too!

Unite your gear
Your ever-growing collection of boutique modular gear, vintage synths, and software instruments can finally perform in unison, thanks to the jaw-dropping connectivity KeyStep Pro has to offer. 4 CV, Gate and Mod outputs, 8 dedicated drum Gate outputs, Clocks, MIDI in, 2 MIDI outs, a solo metronome output, sustain input to let you get expressive with your performance, and USB for easy power and DAW/softsynth control.

Control hardware, software, and your DAW at the same time
If you prefer to create music "in the box", KeyStep Pro can also help your creativity come alive. Easily sequence and arpeggiate your virtual instruments, sync it with your software studio, and switch to the dedicated Control mode to control parameters in your favorite synths and effects. The possibilities are limitless.', 'https://cdn.long-mcquade.com/files/176580/lg_9bdae43e91e9edd9abf514b29a5d321c.webp?alt=KeyStep%20Pro%20Sequencer/Controller'),
(5, 1, 'Alesis','Vortex Wireless 2 Keytar Controller', 44999, 'Take back the stage and experience untethered keytar performance with the next generation Alesis Vortex Wireless 2. Featuring improved ergonomics for better playability, a more durable housing, and an updated control layout, the updated Vortex Wireless 2 offers comprehensive MIDI controller functionality in a stylish and stage-ready keytar design with a stunning gloss-black finish. This dynamic MIDI keytar controller connects wirelessly to your computer and easily integrates with popular virtual instruments, plugins, and DAWs. For maximum stage and studio mobility, the PC- and Mac-compatible USB dongle uses a single USB port to establish a reliable, wireless connection. Create dynamic, expressive performances that the audience will both see and hear.', 'https://cdn.long-mcquade.com/files/98575/lg_51b7a105d1c873468b27f8bb695843e7.webp?alt=Vortex%20Wireless%202%20Keytar%20Controller'),
(6, 1, 'Gretsch Drums','Catalina Maple 7-Piece Shell Pack (22,8,10,12,14,16,SD) - Walnut Glaze', 219999, 'From its sleek, innovative hardware designs and legendary Gretsch-formula shell, Catalina Maple is a favorite among players that want a terrific sounding Gretsch drum set with ergonomically satisfying playing experience and a fresh, contemporary look.

Catalina Maples mounting hardware includes a round gas cap bass drum mount plate and an ultra-low profile GTS mounting system. Gretsch T-Wing screws and bolts are included on all fittings for drummer-friendly feel and rubber isolated die-cast bass drum claws help keep bass drum hoops looking new.

The 7-ply Gretsch-formula maple shell has 30-degree bearing edges and natural shell interiors. Bass drums include telescopic bass drum spurs and matching maple wood bass drum hoops. Toms and snare drums feature 2.3mm triple flanged hoops. All drums are fitted with Remo drum heads.', 'https://cdn.long-mcquade.com/files/120980/lg_a1a6173315a88a4545a4d9ceeebf6c3f.webp?alt=Catalina%20Maple%207-Piece%20Shell%20Pack%20(22,8,10,12,14,16,SD)%20-%20Walnut%20Glaze'),
(6, 1, 'Ludwig Drums','Vistalite Zep 5-Piece Shell Pack (26,14,16,18,SD) - Amber', 487500, 'Notorious for their attack as they are for their stunning crystalline looks, Vistalite acrylic drums are a statement both sonically and visually. Vistalite drums are produced to highest construction standards with reinforced seams and crisp bearing edges for optimum shell integrity and tuning range. Since 1972, Vistalite drums have been performed on and coveted by some of musics top players.
This kit perfectly fits into a classic hard rock/heavy metal settings without compromising amplifiers and the voice of the vocalist. In this case, louder means better.', 'https://cdn.long-mcquade.com/files/136868/lg_688cad3f5051303f30b13e4782182c33.webp?alt=Vistalite%20Zep%205-Piece%20Shell%20Pack%20(26,14,16,18,SD)%20-%20Amber'),
(6, 1, 'Ludwig Drums','Centennial Zep 4-Piece Shell Pack (26,14,16,18) - Green Sparkle', 169500, 'Originally created to recognize Ludwigs 100th Anniversary in 2009, Ludwig Centennial Series Drums have been expanded to include new shell packs in popular, tour-ready configurations. Fusing the warmth and projection of quality North American Maple shells with a choice of six custom sparkle or natural lacquer finishes, the Centennial Series delivers reliabiity and the legendary Ludwig sound in one exceptional package.

The 100% North American Maple Shells are crowned with Vibraband Suspension Rims to ensure supreme resonance, while wearing triple-flanged chrome hoops and redesigned classic lugs. The bass drum features an undrilled design to maintain the natural timbre of the drum. In addition, the die-cast bass drum claws and telescoping spurs ensure a dependable tune and base, respectively.', 'https://cdn.long-mcquade.com/files/194432/lg_16ec14f0a057040589570608027e6b37.webp?alt=Centennial%20Zep%204-Piece%20Shell%20Pack%20(26,14,16,18)%20-%20Green%20Sparkle'),
(7, 1, 'Roland','VAD706 V-Drums Acoustic Design Kit - Gloss Ebony', 1179999, 'The VAD706 takes the electronic drumming experience where its never gone before, combining Rolands flagship V-Drums technologies with the hand-crafted detail of premium-grade acoustic drums. This top-of-the-line V-Drums Acoustic Design kit features digital snare, ride, and hi-hat pads that bring ultra-detailed playability to the three most nuanced pieces in the kit. The next-generation TD-50X module provides unmatched tone, feel, and response, coupled with deep editing tools to fully personalize your sound and pro connectivity to take on any playing situation. Full-size wood shells are included throughout, with advanced sensing systems that deliver real-deal acoustic feel. And with four eye-popping finishes available, you can choose the look that perfectly matches your personal style and taste.', 'https://cdn.long-mcquade.com/files/231406/lg_102081554cda5b740aecc6019dcd79c3.webp?alt=VAD706%20V-Drums%20Acoustic%20Design%20Kit%20-%20Gloss%20Ebony'),
(7, 1, 'Alesis','Strike Pro Special Edition Electronic Drum Kit', 349900, 'The Strike Pro Special Edition is a standard-setting electronic drum kit that features a full-sized 20-inch kick for incredible feel and impact, latest-generation mesh heads for unequalled response and the most capable, versatile drum module ever. The full-sized kick gives drummers an unprecedented degree of response and impact - unmatched by any other electronic kit - enabling the Strike Pro Special Edition to absolutely redefine the playing experience and realism for electronic drums.', 'https://cdn.long-mcquade.com/files/159528/lg_cd2fcee4b885d9918e3365c8697fd45d.webp?alt=Strike%20Pro%20Special%20Edition%20Electronic%20Drum%20Kit'),
(8, 1, 'Boss','Katana-100 MkII Combo Amplifier', 54999, 'Katana MkII takes the acclaimed Katana guitar amp series to the next level, turbocharging the core platform with more sounds, more effects, and more features. Newly voiced variations are now available for all five amp characters, doubling the tonal options. And the onboard effects categories have been expanded from three to five, providing even more real-time processing to choose from. The usability has been ramped up too, with a power amp input for modelers and multi-FX, easy stereo expansion for dual amp setups, updated editor software, and many other enhancements.', 'https://cdn.long-mcquade.com/files/154064/lg_5554e9da168a65ed12a7da4905509777.webp?alt=Katana-100%20MkII%20Combo%20Amplifier'),
(8, 1, 'Vox','C30C2 30 Watt 2x12 Tube Combo', 179999, 'For those who crave more power, the AC30 expands on the captivating sound of its little brother by doubling the wattage. Employing a quartet of EL84 power tubes, the AC30 Custom pumps 30 watts of remarkable tone through a pair of 12" Celestion Greenback speakers. Capable of both enchanting clean and raucous overdriven sounds, the signature chime of the AC30 Custom pairs seamlessly the intricacies of your playing style, resulting in a sound that is truly your own. Perhaps the most iconic amplifier in VOXs pedigree, the AC30 earned its place in history as the amplifier that powered the British Invasion. Since then, the AC30 has remained the choice of the worlds most accomplished artists who have come to rely on its unique voice to amplify theirs.', 'https://cdn.long-mcquade.com/files/8392/lg_lg-ac30c2-angle.webp?alt=AC30C2%2030%20Watt%202x12%20Tube%20Combo'),
(8, 1, 'Fender','65 Deluxe Reverb', 219999, 'The 22-watt (at 8 ohms) 65 Deluxe Reverb amp is for rock, country or blues players who want a moderately powered amp they can crank up on the gig or in the studio. The fat, snappy guitar tones heard on many of our favorite recordings, from Memphis to Abbey Road, were made using the Deluxe amp.

Features include a pair of 6V6 Groove Tube output tubes, one 5AR4 rectifier tube, four 12AX7 preamp tubes, two 12AT7 tubes, one 12 8-ohm Jensen C-12K speaker, dual channels (normal and vibrato), tube-driven Fender reverb, tube vibrato, two-button footswitch for reverb and vibrato on-off, black textured vinyl covering and silver grille cloth.', 'https://cdn.long-mcquade.com/files/835/lg_2174.webp?alt=\%2765%20Deluxe%20Reverb'),
(9, 1, 'Fender','Rumble Stage 800 WiFi/Bluetooth-Enabled Digital Bass Amp', 124999, 'Perfect for rehearsing and recording, the Rumble Stage 800 harnesses the potent processing power of our GT engine to deliver an arenas worth of realistic bass amp and effects models. Create your own sound and get inspired with over 15 amp models and 40 effects - all controllable via Bluetooth and the exclusive Fender Tone app.

As the worlds first WiFi-equipped bass amplifier, Rumble Stage 800 makes it easy to explore contemporary sounds and update your palette for new sonic possibilities. With the Fender Tone app, its easy to download the latest updates, add new amp and effects models, access Fender artist-created presets, and connect directly with a community of other creative players and music makers.', 'https://cdn.long-mcquade.com/files/100484/lg_c9e204c387abc186f8d3964693e70f92.webp?alt=Rumble%20Stage%20800%20WiFi/Bluetooth-Enabled%20Digital%20Bass%20Amp'),
(9, 1, 'Ampeg','Rocket Bass RB-210 500 Watt 2x10 Combo Bass Amp', 84999, 'The 500-watt Ampeg® Rocket Bass® RB-210 combo bass amp offers unparalleled performance, stunning 60s-style looks, and a robust feature set in a light and portable package - making it the ideal gigging amp. Like its legendary larger siblings, the RB-210 combo offers classic Ampeg 3-band EQ and Ultra Hi/Ultra Lo switches, which tone aficionados know are critical to sculpting the perfect bass sound. Plus, a newly designed switchable Super Grit Technology™ verdrive circuit with independent Grit and Level controls adds warm and gutsy growl. A mutable high-frequency horn complements the dual 10" Eminence® speakers. An effects loop and extension speaker output add flexibility, an auxiliary input lets you play along with external audio, a headphone output ensures youll be able to practice whenever you like, and the XLR direct output provides a professional connection to a P.A. or recorder.', 'https://cdn.long-mcquade.com/files/227226/lg_502076612c002be1e51a501a8e659884.webp?alt=Rocket%20Bass%20RB-210%20500%20Watt%202x10%20Combo%20Bass%20Amp'),
(10, 1, 'Boss','RC-600 Loop Station Pedal', 92999, 'Meet the RC-600, the most advanced looper on the planet. Loaded with evolved features and customizable functions, this next-generation Loop Station ushers in a new era of creative power for guitarists, singer/songwriters, multi-instrumentalists, and other looping musicians. Capture multiple mics and instruments with six stereo tracks and premium 32-bit sound, and take full command with nine freely assignable footswitches and deep external control support. And thats just the start - you can also color loops with a massive FX selection, groove with onboard rhythms, route audio as you like to the three stereo outputs, integrate with computer software via USB, and much more.', 'https://cdn.long-mcquade.com/files/276726/lg_24d77f4c7c96eac598df7e7709fd4a07.webp?alt=RC-600%20Loop%20Station%20Pedal'),
(10, 1, 'Ibanez','TS-9 Tube Screamer', 15399, 'The warmth of tube amps has been the goal for most of the over-drive pedals that exist. However, the Tube Screamer has been the choice 2nd to none by people searching for the best, because it lets the guitar sing so well in its original voice. The tone can be heard in playing by countless musicians over the years and still keeps fascinating new generations.', 'https://cdn.long-mcquade.com/files/2996/lg_ts9.webp?alt=TS9%20-%20Tube%20Screamer'),
(10, 1, 'MXR','M169 - Carbon Copy Analog Delay', 23699, 'The MXR Carbon Copy Analog Delay Pedal features a completely analog audio path for the ultimate in rich, warm delay-made possible only by old-school bucket brigade technology. This design boasts an amazing 600ms of delay time with optional modulation via a top-mounted switch and a simple, three-knob layout that controls Delay time, Mix (dry/wet blend), and Regen (delay repeats)-all in a pedal no bigger than a Phase 90. In addition, the M169 pedal has two internal trim pots that offer user-adjustable width and rate control of the modulation for even more tonal options. The Carbon Copy effect pedal will take you from crisp "bathroom" slap echoes to epic, Gilmour-esque delays with a twist of a knob. True hard-wire bypass, single 9-volt operation, and stage-ready blue LEDs round out the package.', 'https://cdn.long-mcquade.com/files/2443/lg_carbona.webp?alt=M169%20-%20Carbon%20Copy%20Analog%20Delay'),
(10, 1, 'Pedaltrain','Classic 2 Pedal Board with Soft Case', 22999, 'Pedaltrains all-new Classic Series is rooted in the companys best-selling pedal board models. Pedaltrain has incorporated design improvements that make these models better than ever. Based on the original PT-2, the Classic 2 features Pedaltrains original four-rail design and traditional rail spacing.', 'https://cdn.long-mcquade.com/files/61109/lg_fb198d34380e2ee286e84617bbba9de7.webp?alt=Classic%202%20Pedal%20Board%20with%20Soft%20Case'),
(10, 1, 'Neural DSP','Quad Cortex Amp/FX Processor', 259900, 'Vulgar Display of Power
Quad Cortex is the most powerful floor modeler on the planet. With 2GHz of dedicated DSP from its Quad-Core SHARC architecture, this ludicrous amount of processing capacity provides limitless sound design possibilities.

Neural Capture
Capture, share and download your favorite rigs sounds. Equipped with unique biomimetic AI technology, Quad Cortex can learn and replicate the sonic characteristics of any physical amplifier, overdrive, and cabinet with unprecedented accuracy.

Unlike any other, the sophisticated neural network algorithm perceives sound akin to human perception, making it the most natural-sounding capture solution on the planet.

Neural has collaborated with some of the best producers and sound designers to provide an ever-growing collection of free rig captures in addition to the full-circuit models.', 'https://cdn.long-mcquade.com/files/214715/lg_4c566f2198f98451a07c39d078564158.webp?alt=Quad%20Cortex%20Amp/FX%20Processor'),
(10, 1, 'Maestro Effects','Comet Chorus Pedal', 22900, 'The Comet uses iconic analog bucket brigade device (BBD) technology to deliver warm, classic chorus tones. This all-analog pedal boasts a Mode toggle switch for increased sonic versatility. The Earth mode provides an optimized, shimmering chorus effect, while Orbit mode adds some amplitude modulation to the chorused sound, more accurately simulating the sonic complexities of a rotary speaker. An internal trim pot lets you adjust the level of the rotary speaker Orbit effect to taste. The intuitive 3-knob layout lets you quickly dial up the Depth (amount of pitch variation), Speed (modulation rate) of the chorusing, and adjust the amount of pitch modulated signal that is blended in with the dry signal by using the Mix control. The true bypass footswitch triggers the LED lights in the bugles in the Maestro logo when its on, so youll always know when the effect is active.', 'https://cdn.long-mcquade.com/files/264181/lg_a147d148b5da1da13762257bc0a0d7d9.?alt=Comet%20Chorus%20Pedal');
